### ISSUE TITLE
Disallowed Host: Invalid HTTP_HOST

### ISSUE THREAD

**Issue by lolob** [boundlessgeo/exchange#428]
Hello.

I run exchange using docker following the instructions given. I have modified the original exchange/docker-compose.yml to use different external ip address. Where to modify the ALLOWED_HOSTS so I can enter a new one. I had tried one in exchange folder and one in geonode folder.

**Comment by walker** [comment]
Hey @lolob, you mean a different docker-machine IPs? You'd need to change it in `exchange/docker/home/local_settings.py`, I believe.

**Comment by lolob** [comment]
Dear @walker ,
Yes I changed the docker-machine IPs with 192.168.1.0/24
I still receive the error. I paste the exchange log below.

> exchange     | Traceback (most recent call last):
> exchange     |   File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
> exchange     |     self.result = application(self.environ, self.start_response)
> exchange     |   File "/env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
> exchange     |     return self.application(environ, start_response)
> exchange     |   File "/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
> exchange     |     response = self.get_response(request)
> exchange     |   File "/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 207, in get_response
> exchange     |     return debug.technical_500_response(request, *sys.exc_info(), status_code=400)
> exchange     |   File "/env/lib/python2.7/site-packages/django/views/debug.py", line 97, in technical_500_response
> exchange     |     html = reporter.get_traceback_html()
> exchange     |   File "/env/lib/python2.7/site-packages/django/views/debug.py", line 384, in get_traceback_html
> exchange     |     return t.render(c)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 210, in render
> exchange     |     return self._render(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
> exchange     |     return self.nodelist.render(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 905, in render
> exchange     |     bit = self.render_node(node, context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
> exchange     |     return node.render(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
> exchange     |     return nodelist.render(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 905, in render
> exchange     |     bit = self.render_node(node, context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
> exchange     |     return node.render(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
> exchange     |     output = self.filter_expression.resolve(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 648, in resolve
> exchange     |     obj = self.var.resolve(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 789, in resolve
> exchange     |     value = self._resolve_lookup(context)
> exchange     |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
> exchange     |     current = current()
> exchange     |   File "/env/lib/python2.7/site-packages/django/http/request.py", line 152, in build_absolute_uri
> exchange     |     host=self.get_host(),
> exchange     |   File "/env/lib/python2.7/site-packages/django/http/request.py", line 102, in get_host
> exchange     |     raise DisallowedHost(msg)
> exchange     | DisallowedHost: Invalid HTTP_HOST header: '192.168.1.203'. You may need to add u'192.168.1.203' to ALLOWED_HOSTS.
> exchange     | [10/Nov/2017 01:08:38] "HEAD / HTTP/1.1" 500 59
> exchange     | - Broken pipe from ('192.168.1.203', 57452)
> exchange     | [07:08:38] Stopped waiting for django after 60 tries
> exchange exited with code 1

Below is my snippet from docker-compose.yml

```
networks:
    # Explicitly-defined internal network for containers to talk to each other
    internal:
        ipam:
            config:
              - subnet: 172.16.237.0/24
                gateway: 172.16.237.1
    # Network for exposing IPs for access from the host, e.g. your browser
    external:
        driver: macvlan
        driver_opts:
                   parent: enp3s0
        ipam:
            config:
              - subnet: 192.168.1.0/24
                gateway: 192.168.1.254
-
-
-
-
exchange:
        env_file: .env
        container_name: exchange
        image: quay.io/boundlessgeo/bex:master
        # see ./Dockerfile which defines the whole setup
        build: .

        links:
            - database
            - queue
            - geoserver

        # Code in volumes shared with host, so edits are immediately visible.
        volumes:
            - scratch:/scratch

            # Add a MapLoom home
            - $MAPLOOM_HOME:/mnt/maploom:ro

            # Ideally, all volumes shared with host are mounted read-only.
            # But we have to pip install -e /mnt/geonode to ensure GeoNode's
            # dependencies are all installed per its setup.py.
            # And pip insists on writing its .egg-info to the source directory.
            # 'python setup.py develop' might be a workaround if GeoNode's
            # setup.py used setuptools, but it doesn't so that fails.
            - $GEONODE_HOME:/mnt/geonode

            # Exchange code that dev will presumably want to change.
            - $EXCHANGE_HOME:/mnt/exchange:rw

            # Example of how to mount something else from here.
            # - $HOME/stuff/django-osgeo-importer:/mnt/django-osgeo-importer:ro

        networks:
            internal:
            external:
                ipv4_address: 192.168.1.203
```
